### ISSUE TITLE
Not getting the correct result

### ISSUE THREAD

**Issue by JosephKKim** [fepegar/staple#49]
* staple version: Latest
* Python version: 3.7.15
* Operating System: Ubuntu 20.04

### Description

I am trying to make STAPLE ground truth using the source code you have provided.
Dataset that I am considering is retinal vessel dataset (2D binary segmentation dataset) are listed below, which have
2 and 3 annotation respectively.
[ChaseDB1](https://blogs.kingston.ac.uk/retinal/chasedb1/)
[STARE](https://cecas.clemson.edu/~ahoover/stare/probing/index.html)

### What I Did

```
staple STARE_ah.png STARE_vk.png STARE_result.png STARE_staple.png

ValueError: Maximum number of iterations reached before convergence
```

I have converted ppm file into png file and ran staple with the command I have stated above. 

And even when it converged it provided an image filled with black. 
![Image_staple](https://user-images.githubusercontent.com/56065530/237050917-4fcd8355-32a2-42b7-9180-5e7eb5b918cb.png)

In this case what would be the problem?

Thanks in advance!

**Comment by fepegar** [comment]
Hi, @JosephKKim. I won't be able to debug this. I suggest you use a different implementation, as suggested in the README. Good luck!
